apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "ghcr.io/lucaspickering/laulud-api:{{ .Values.versionSha }}"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          env:
            - name: ROCKET_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: ROCKET_DATABASE_URL
              value: mongodb://db:27017/?appname=laulud
            - name: ROCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret-key
                  key: secret-key
            - name: ROCKET_SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify-client-creds
                  key: id
            - name: ROCKET_SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-client-creds
                  key: secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: api
