# TODO set up encryption and RBAC for secrets https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: api-secret-key
type: generic
data:
  secret-key: "{{ .Values.apiSecretKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: spotify-client-creds
type: generic
data:
  id: "{{ .Values.spotifyClientId | b64enc }}"
  secret: "{{ .Values.spotifyClientSecret | b64enc }}"
