version: "3.7"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_build:
  ui_node_modules:

services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"

  api:
    build: ./api
    working_dir: /app/api
    command: cargo watch -w Cargo.toml -w Cargo.lock -w src/ -x run
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    volumes:
      - ./:/app
      - api_build:/app/api/target
    depends_on:
      - db
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: ${RUST_LOG:-info,laulud_api=debug}
      # Grab these from the .env file
      ROCKET_SPOTIFY_CLIENT_ID:
      ROCKET_SPOTIFY_CLIENT_SECRET:
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    working_dir: /app/ui
    command: sh -c "npm install && npm run start"
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    environment:
      WEBPACK_HOST: 0.0.0.0
      LAULUD_API_HOST: http://api:8000
    volumes:
      - ./ui:/app/ui
      - ./api/schema.graphql:/app/ui/schema.graphql
      - ui_node_modules:/app/ui/node_modules
    ports:
      - "3000:3000"
