version: "3.7"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_build:
  ui_node_modules:

services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"

  api:
    build: api/
    command: cargo watch -x run
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    volumes:
      - ./api:/app:rw
      - api_build:/app/target
    depends_on:
      - db
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "8000:8000"

  ui:
    build: ui/
    command: sh -c "npm install && npm run start | cat" # pipe to cat so console does not get reset
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    environment:
      LAULUD_API_HOST: http://api:8000
      HTTPS: "true" # Needed for Spotify login
    volumes:
      - ./ui:/app:rw
      - ui_node_modules:/app/node_modules
    ports:
      - "3000:3000"
