[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
edition = "2018"
license = "MIT"
name = "laulud-api"
version = "0.1.0"

[dependencies]
config = "0.10"
mongodb = {version = "1.1", default-features = false, features = ["tokio-runtime"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tide = "0.14"
tokio = {version = "0.3", features = ["full"]}
uuid = "0.8"
