[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
edition = "2018"
license = "MIT"
name = "laulud-api"
version = "0.1.0"

[dependencies]
config = "0.10"
mongodb = {version = "1.1", default-features = false, features = ["tokio-runtime"]}
rocket = {git = "https://github.com/SergioBenitez/Rocket.git", branch = "master"}
rocket_contrib = {git = "https://github.com/SergioBenitez/Rocket.git", branch = "master"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
strum = {version = "0.19", features = ["derive"]}
tokio = {version = "0.2", features = ["full"]}
uuid = "0.8"
